version: '3'

services:
  goapp: 
    build: goapp
    platform: linux/amd64
    volumes:
      - ./goapp:/app
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysql
    networks:
      - wallet
  
  pyapp: 
    build: pyapp
    platform: linux/amd64
    environment:
      BROKER_URL: fc_kafka:29092
      BROKER_GROUP_ID: wallet
      DATABASE_URL: mysql+pymysql://root:root@mysql:3306/wallet
    volumes:
      - ./pyapp:/app
    ports:
      - 3003:3003
    expose:
      - 3003
    depends_on:
      - mysql
    networks:
      - wallet

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - .docker/mysql:/var/lib/mysql
    networks:
      - wallet

  fc_zookeeper:
    image: "confluentinc/cp-zookeeper:6.1.0"
    container_name: fc_zookeeper
    ports:
      - 2181:2181
    environment:
      TZ: Sao_Paulo/Brazil
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - wallet
    
  fc_kafka:
    image: "confluentinc/cp-enterprise-kafka:6.1.0"
    container_name: fc_kafka
    depends_on:
      - fc_zookeeper
    ports:
    # Exposes 9092 for external connections to the broker
    # Use kafka:29092 for connections internal on the docker network
    # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
      - '9092:9092'
    environment:
      TZ: Sao_Paulo/Brazil
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: fc_zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fc_kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      CONFLUENT_METRICS_ENABLE: 'false'
    networks:
      - wallet
      
  control-center:
    image: confluentinc/cp-enterprise-control-center:7.3.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - fc_kafka
    ports:
      - "9021:9021"
    expose:
      - 9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'fc_kafka:29092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
    networks:
      - wallet

networks:
  wallet:
    driver: bridge
